`timescale 1ns/1ps
module ltssm_top_2;
 
 reg clk=0;
 reg reset;
 reg[15:0]pipe_rx_data[0:15];
 logic[15:0]pipe_tx_data[0:15];
 event ev,ev2;
 int c_to_tb;

 bit[15:0]ts1_send_cnt[0:15];
 bit[15:0]ts2_send_cnt[0:15];
 bit[15:0]ts1_rcv_cnt[0:15];
 bit[15:0]ts2_rcv_cnt[0:15];
 bit[8*20:0]state_ascii_tb;
 int ts1_sent_cnt,ts1_rcvd_cnt;
 int ts2_sent_cnt,ts2_rcvd_cnt;
 bit flag_detect,flag_pol_active_send,flag_pol_active_receive,flag_pol_config_send,flag_pol_config_receive;
 int fd_3;
 int l;
 int tracker_pl;
 int tracker_pl_tx,tracker_pl_rx;
 

 ltssm_x DUT(.clk(clk),
           .reset(reset),
	   .pipe_tx_data(pipe_rx_data),
           .pipe_rx_data(pipe_tx_data)
           );
always #5 clk=~clk;

  task send_ts1;
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h4a4a;
    end
    @(negedge clk);
     for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'hf7bc;
    end
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h4ef7;
    end
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h307e;
    end

  endtask

  task send_ts2;
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h4545;
    end
    @(negedge clk);
     for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'hf7bc;
    end
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h4ef7;
    end
    @(negedge clk);
    for(int i=0;i<=15;i++)begin
     pipe_tx_data[i]=16'h327e;
    end
  endtask

  initial begin
    fd_3=$fopen("state_trans.txt","w");
    tracker_pl_tx=$fopen("tracker_pl_tx","w"); 
    $fdisplay(tracker_pl_tx,"======================================================================================="); 
    $fdisplay(tracker_pl_tx,"| Tracker generated by: Shyam Gudikandula");  
    $fdisplay(tracker_pl_tx,"| Tracker structure reference: BRECK project");
    $fdisplay(tracker_pl_tx,"=======================================================================================\n\n"); 
    $fdisplay(tracker_pl_tx,"-----------------------------TX------------------------------------------------------------------------------RX------------------------------------------------------");
    reset=1;
    @(negedge clk);
    reset=0;
    $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               ltssm in DETECT",$time);	           
    #5;

    fork
      begin	  
        forever begin
          fork	    
            begin//Timeout thread for states in tb begin
              forever begin
                @(negedge clk);		
                if(state_ascii_tb == "CONFIGURATION") begin
                  c_to_tb++;	  
                  if(c_to_tb == 200) begin
                    state_ascii_tb="DETECT";
                    c_to_tb=0;
                    ts1_send_cnt[0]=0;
                    ts2_send_cnt[0]=0;
		    ts1_sent_cnt=0;
		    ts2_sent_cnt=0;
                  end
		  if(pipe_rx_data[0]==16'h4a4a)
	           ts1_rcvd_cnt++;
	          if(pipe_rx_data[0]==16'h4545)
	           ts2_rcvd_cnt++;
               end
              end
            end//Timeout thread for states in tb begin
           
            begin
              forever begin
                @(negedge clk);
		if(state_ascii_tb == "DETECT") begin
		  if(pipe_rx_data[0]==16'h4a4a)
	           ts1_rcvd_cnt++;
	          if(pipe_rx_data[0]==16'h4545)
	           ts2_rcvd_cnt++;
		end
	      end
	    end	    

            begin//outer thread-0 begin
	      if(l==0)
              @(negedge clk);
              forever begin
                if(state_ascii_tb=="DETECT" || state_ascii_tb=="POL_ACTIVE") begin
                  send_ts1();
                  ts1_send_cnt[0]++;
		  ts1_sent_cnt++;
                end
                else if(state_ascii_tb=="POL_CONFIG") begin
                  send_ts2();
                  ts2_send_cnt[0]++;
		  ts2_sent_cnt++;
                end
                else if(state_ascii_tb=="CONFIGURATION") begin
                  send_ts1();
		  ts1_sent_cnt++;
                end
              end
              $display("Thread-0 completed at time:%0tns",$time);
            end//outer thread-0 end

            begin//outer thread-1 begin
              forever begin
                @(negedge clk);
                state_ascii_tb="DETECT";
                if(ts1_send_cnt[0]==5) begin
                  @(negedge clk);		  
                  ts1_send_cnt[0]=0;
                  flag_detect=1;
                end
                if(flag_detect==1)
                  break;
              end
              forever begin
                @(negedge clk);
                wait(state_ascii_tb=="POL_ACTIVE");
                if(ts1_send_cnt[0]==16) begin
                  @(negedge clk);
                  ts1_send_cnt[0]=0;
                  flag_pol_active_send=1;
                end
                if(flag_pol_active_send==1)
                 break;
              end
              
              
              forever begin
                @(negedge clk);
                wait(state_ascii_tb=="POL_CONFIG");
                if(ts2_send_cnt[0]==16) begin
                  @(negedge clk);
                  ts2_send_cnt[0]=0;
                  flag_pol_config_send=1;
                end
                if(flag_pol_config_send==1)
                 break;
              end
              #9000;
              $display("Thread-1 completed at time:%0tns",$time);
            end//outer thread-1 end

            begin//outer thread-2 begin
              forever begin
                @(negedge clk);
                wait(state_ascii_tb=="POL_ACTIVE");
		if(pipe_rx_data[0]==16'h4545)
	         ts2_rcvd_cnt++;
                if(pipe_rx_data[0]==16'h4a4a) begin
                  ts1_rcv_cnt[0]++;
		  ts1_rcvd_cnt++;
                end
                if(ts1_rcv_cnt[0]==8) begin
                  @(negedge clk);
                  ts1_rcv_cnt[0]=0;
                  flag_pol_active_receive=1;
                end
                if(flag_pol_active_receive==1)
                 break;
              end
              
              forever begin
                @(negedge clk);
                wait(state_ascii_tb=="POL_CONFIG");
		if(pipe_rx_data[0]==16'h4a4a)
		  ts1_rcvd_cnt++;
                if(pipe_rx_data[0]==16'h4545) begin
                  ts2_rcv_cnt[0]++;
		  ts2_rcvd_cnt++;
                end
                if(ts2_rcv_cnt[0]==8) begin
                  @(negedge clk);
                  ts2_rcv_cnt[0]=0;
                  flag_pol_config_receive=1;
                end
                if(flag_pol_config_receive==1)
                 break;
              end
              wait(ev.triggered);
              $display("Thread-2 completed at time:%0tns",$time);
            end//outer thread-2 end

            
            begin//outer thread-3 begin
              forever begin
                @(negedge clk);
                if(flag_detect==1) begin
                  $fdisplay(fd_3,$sformatf("Enetered the flag_detect state at : %0tns",$time));
                  state_ascii_tb = "POL_ACTIVE";
                  flag_detect=0;
		  ts1_sent_cnt=0;
		  ts1_rcvd_cnt=0;
		  ts2_sent_cnt=0;
		  ts2_rcvd_cnt=0;
                end
                else if(flag_pol_active_send && flag_pol_active_receive) begin
                  $fdisplay(fd_3,$sformatf("Enetered the flag_pol_active state at : %0tns",$time));
                  @(negedge clk);		  
                  state_ascii_tb="POL_CONFIG";
                  flag_pol_active_send=0;
                  flag_pol_active_receive=0;
		  ts1_sent_cnt=0;
		  ts1_rcvd_cnt=0;
		  ts2_sent_cnt=0;
		  ts2_rcvd_cnt=0;
                end
                else if(flag_pol_config_send && flag_pol_config_receive) begin
                  $fdisplay(fd_3,$sformatf("Enetered the configuration state at : %0tns",$time));
                  @(negedge clk);
                  state_ascii_tb="CONFIGURATION";
                  flag_pol_config_send=0;
                  flag_pol_config_receive=0;
		  ts1_sent_cnt=0;
		  ts1_rcvd_cnt=0;
		  ts2_sent_cnt=0;
		  ts2_rcvd_cnt=0;
                  repeat(210)
                    @(negedge clk);
                    ->ev;
                end 

              end
              $display("Thread-3 completed at time:%0tns",$time);
            end//outer thread-3 end


           begin
	     forever begin
	       @(posedge clk);	     
	       if(pipe_tx_data[0]==16'h4a4a) begin
	         $fdisplay(tracker_pl_tx,"%0t                                                                                                                                                                                 >TS1(%0d)",$time,ts1_sent_cnt);
		@(posedge clk);
	         if(pipe_tx_data[0]==16'h4a4a) begin
	         
		 end	 
               end	       
	       if(pipe_tx_data[0]==16'h4545) begin
	         $fdisplay(tracker_pl_tx,"%0t                                                                                                                                                                                 >TS2(%0d)",$time,ts2_sent_cnt);	           
	     end
            end 
           end
           begin
	     forever begin
	       @(posedge clk);	     
	       if(pipe_rx_data[0]==16'h4a4a)	       
	       $fdisplay(tracker_pl_tx,"%0t                                                                                                                                                                                 <TS1(%0d)",$time,ts1_rcvd_cnt);	
	       if(pipe_rx_data[0]==16'h4545)
	       $fdisplay(tracker_pl_tx,"%0t                                                                                                                                                                                 <TS2(%0d)",$time,ts2_rcvd_cnt);	
	    end 
           end

          begin
            //@(posedge clk);		  
	        //$fdisplay(tracker_pl,"                                                                                                                                                                               ltssm in DETECT");	           
            forever begin
              @(posedge clk);
	      if(flag_detect==1) 
	        $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               ltssm in POLLING_ACTIVE",$time);	           
	      if(flag_pol_active_send && flag_pol_active_receive) begin 
		@(posedge clk);      
	        $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               ltssm in POLLING_CONFIG",$time);	           
	      end	
	      if(flag_pol_config_send && flag_pol_config_receive) begin
		@(posedge clk);      
	        $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               ltssm in CONFIGURATION",$time);
              end		
	      
	      if(c_to_tb==199) begin 
	        $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               timer expired direct to detect state",$time);	           
	        $fdisplay(tracker_pl_tx,"%0tns                                                                                                                                                                               ltssm in DETECT",$time);	           
             end
	   end
	  end

          /*begin
            forever begin
              @(posedge clk);
	      if(pipe_tx_data[0]==16'h4a4a || pipe_tx_data[0]==16'h4545)
	       ++send_cnt;
	      if(pipe_rx_data[0]==16'h4a4a || pipe_rx_data[0]==16'h4545)
	       ++rcv_cnt;
              /*if(!($unchanged(state_ascii_tb)))begin
                send_cnt=0;
		rcv_cnt=0;
	      end
	    end
	  end*/
  	

       begin
         forever begin
           @(posedge clk);
	   if(pipe_tx_data[0] != 16'h0000) begin
           $fwrite(tracker_pl_tx,"%0t\t",$time);
	   if(pipe_tx_data[0][7:0]==8'hbc)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx,"COM ");
	   if(pipe_tx_data[0][7:0]==8'hf7)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx,"PAD ");
         
	    	   
           if(pipe_tx_data[0][7:0] != 8'hbc && pipe_tx_data[0][7:0] != 8'hf7) begin
           for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx,"%h  ",pipe_tx_data[i][7:0]);
           end
             $fwrite(tracker_pl_tx," | ");
	     
	   if(pipe_rx_data[0][7:0]==8'hbc)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx," COM ");
	   if(pipe_rx_data[0][7:0]==8'hf7)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx," PAD ");
           
           if(pipe_rx_data[0][7:0] != 8'hbc && pipe_rx_data[0][7:0] != 8'hf7) begin
	   for(int k=0;k<=15;k++)
             $fwrite(tracker_pl_tx," %h  ",pipe_rx_data[k][7:0]);
           end
            $fdisplay(tracker_pl_tx,"");
	    
           $fwrite(tracker_pl_tx,"%0t\t",$time);
	   if(pipe_tx_data[0][15:8]==8'hf7)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx,"PAD ");

           if(pipe_tx_data[0][15:8] != 8'hf7) begin
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx,"%h  ",pipe_tx_data[i][15:8]);
           end
             $fwrite(tracker_pl_tx," | ");
	   if(pipe_rx_data[0][15:8]==8'hf7)
	   for(int i=0;i<=15;i++)
             $fwrite(tracker_pl_tx," PAD ");

           if(pipe_rx_data[0][15:8] != 8'hf7) begin
	   for(int k=0;k<=15;k++)
             $fwrite(tracker_pl_tx," %h  ",pipe_rx_data[k][15:8]);
           end
            $fdisplay(tracker_pl_tx,"");

	  end

        end
       end
            
          join_any
          l++;
          $display("ITERATION :%0d completed at time :%0tns",l,$time);
          disable fork;
        end
      end

      begin
        #100000;
        $display("Completed overall timeout at time:%0tns",$time);
      end
    join_any 
      
 $finish;

  end

  endmodule
